# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName("MainWindow")
        
        MainWindow.resize(494, 598)
        MainWindow.setMaximumSize(QtCore.QSize(494, 598))
        MainWindow.setMinimumSize(QtCore.QSize(494, 598))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(0.98)
        MainWindow.setStyleSheet("background-color: rgb(48, 38, 38);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(10, 10, 471, 100))
        self.lcdNumber.setMaximumHeight(90)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        
        self.lcdNumber.setFont(font)
        self.lcdNumber.setDigitCount(10)
        self.lcdNumber.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcdNumber.setObjectName("lcdNumber")
        
        self.pushButton0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton0.setGeometry(QtCore.QRect(130, 520, 115, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        self.pushButton0.setFont(font)
        self.pushButton0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton0.setStyleSheet("QPushButton{background-color: rgb(9, 8, 8);\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.pushButton0.setObjectName("pushButton0")
        self.equals_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.equals_pushButton.setGeometry(QtCore.QRect(370, 520, 115, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.equals_pushButton.setFont(font)
        self.equals_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.equals_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(29, 25, 26);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.equals_pushButton.setObjectName("equals_pushButton")
        self.deci_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.deci_pushButton.setGeometry(QtCore.QRect(250, 520, 115, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.deci_pushButton.setFont(font)
        self.deci_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deci_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(29, 25, 26);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.deci_pushButton.setObjectName("deci_pushButton")
        self.dl_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.dl_pushButton.setGeometry(QtCore.QRect(10, 520, 115, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.dl_pushButton.setFont(font)
        self.dl_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dl_pushButton.setCheckable(True)
        self.dl_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(29, 25, 26);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.dl_pushButton.setObjectName("dl_pushButton")
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(10, 440, 115, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        self.pushButton1.setFont(font)
        self.pushButton1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton1.setStyleSheet("QPushButton{background-color: rgb(9, 8, 8);\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(130, 440, 115, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        self.pushButton2.setFont(font)
        self.pushButton2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton2.setStyleSheet("QPushButton{background-color: rgb(9, 8, 8);\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton3.setGeometry(QtCore.QRect(250, 440, 115, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        self.pushButton3.setFont(font)
        self.pushButton3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton3.setStyleSheet("QPushButton{background-color: rgb(9, 8, 8);\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.pushButton3.setObjectName("pushButton3")
        self.pushButton5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton5.setGeometry(QtCore.QRect(130, 360, 115, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        self.pushButton5.setFont(font)
        self.pushButton5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton5.setStyleSheet("QPushButton{background-color: rgb(9, 8, 8);\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.pushButton5.setObjectName("pushButton5")
        self.pushButton4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton4.setGeometry(QtCore.QRect(10, 360, 115, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        self.pushButton4.setFont(font)
        self.pushButton4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton4.setStyleSheet("QPushButton{background-color: rgb(9, 8, 8);\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.pushButton4.setObjectName("pushButton4")
        self.pushButton6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton6.setGeometry(QtCore.QRect(250, 360, 115, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        self.pushButton6.setFont(font)
        self.pushButton6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton6.setStyleSheet("QPushButton{background-color: rgb(9, 8, 8);\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.pushButton6.setObjectName("pushButton6")
        self.pushButton9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton9.setGeometry(QtCore.QRect(250, 280, 115, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        self.pushButton9.setFont(font)
        self.pushButton9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton9.setStyleSheet("QPushButton{background-color: rgb(9, 8, 8);\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.pushButton9.setObjectName("pushButton9")
        self.pushButton8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton8.setGeometry(QtCore.QRect(130, 280, 115, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        self.pushButton8.setFont(font)
        self.pushButton8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton8.setStyleSheet("QPushButton{background-color: rgb(9, 8, 8);\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.pushButton8.setObjectName("pushButton8")
        self.pushButton7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton7.setGeometry(QtCore.QRect(10, 280, 115, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        self.pushButton7.setFont(font)
        self.pushButton7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton7.setStyleSheet("QPushButton{background-color: rgb(9, 8, 8);\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.pushButton7.setObjectName("pushButton7")
        self.add_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.add_pushButton.setGeometry(QtCore.QRect(370, 440, 115, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.add_pushButton.setFont(font)
        self.add_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(29, 25, 26);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.add_pushButton.setObjectName("add_pushButton")
        self.minus_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.minus_pushButton.setGeometry(QtCore.QRect(370, 360, 115, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.minus_pushButton.setFont(font)
        self.minus_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minus_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(29, 25, 26);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.minus_pushButton.setObjectName("minus_pushButton")
        self.mul_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.mul_pushButton.setGeometry(QtCore.QRect(370, 280, 115, 70))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(22)
        self.mul_pushButton.setFont(font)
        self.mul_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mul_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(29, 25, 26);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.mul_pushButton.setObjectName("mul_pushButton")
        self.div_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.div_pushButton.setGeometry(QtCore.QRect(370, 200, 115, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.div_pushButton.setFont(font)
        self.div_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.div_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(29, 25, 26);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.div_pushButton.setObjectName("div_pushButton")
        self.c_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.c_pushButton.setGeometry(QtCore.QRect(130, 200, 115, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.c_pushButton.setFont(font)
        self.c_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.c_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(29, 25, 26);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.c_pushButton.setObjectName("c_pushButton")
        self.pi_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pi_pushButton.setGeometry(QtCore.QRect(10, 200, 115, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.pi_pushButton.setFont(font)
        self.pi_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pi_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(29, 25, 26);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.pi_pushButton.setObjectName("pi_pushButton")
        self.upon_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.upon_pushButton.setGeometry(QtCore.QRect(370, 139, 115, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.upon_pushButton.setFont(font)
        self.upon_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.upon_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(29, 25, 26);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.upon_pushButton.setObjectName("upon_pushButton")
        self.pow_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pow_pushButton.setGeometry(QtCore.QRect(250, 139, 115, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pow_pushButton.setFont(font)
        self.pow_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pow_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(29, 25, 26);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.pow_pushButton.setObjectName("pow_pushButton")
        self.root_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.root_pushButton.setGeometry(QtCore.QRect(130, 139, 115, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.root_pushButton.setFont(font)
        self.root_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.root_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(29, 25, 26);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.root_pushButton.setObjectName("root_pushButton")
        self.percent_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.percent_pushButton.setGeometry(QtCore.QRect(10, 139, 115, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.percent_pushButton.setFont(font)
        self.percent_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.percent_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(29, 25, 26);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.percent_pushButton.setObjectName("percent_pushButton")
        self.back_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.back_pushButton.setGeometry(QtCore.QRect(250, 200, 115, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.back_pushButton.setFont(font)
        self.back_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(29, 25, 26);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(166, 151, 155);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(166, 151, 155);\n"
"}")
        self.back_pushButton.setIconSize(QtCore.QSize(64, 64))
        self.back_pushButton.setObjectName("back_pushButton")
    
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        
        self.pushButton0.setText(_translate("MainWindow", "0"))
        self.pushButton0.setShortcut(_translate("MainWindow", "0"))
        self.equals_pushButton.setText(_translate("MainWindow", "="))
        self.equals_pushButton.setShortcut(_translate("MainWindow", "=, Return"))
        self.deci_pushButton.setText(_translate("MainWindow", "."))
        self.deci_pushButton.setShortcut(_translate("MainWindow", "."))
        self.dl_pushButton.setText(_translate("MainWindow", "Dark/Light"))
        self.pushButton1.setText(_translate("MainWindow", "1"))
        self.pushButton1.setShortcut(_translate("MainWindow", "1"))
        self.pushButton2.setText(_translate("MainWindow", "2"))
        self.pushButton2.setShortcut(_translate("MainWindow", "2"))
        self.pushButton3.setText(_translate("MainWindow", "3"))
        self.pushButton3.setShortcut(_translate("MainWindow", "3"))
        self.pushButton5.setText(_translate("MainWindow", "5"))
        self.pushButton5.setShortcut(_translate("MainWindow", "5"))
        self.pushButton4.setText(_translate("MainWindow", "4"))
        self.pushButton4.setShortcut(_translate("MainWindow", "4"))
        self.pushButton6.setText(_translate("MainWindow", "6"))
        self.pushButton6.setShortcut(_translate("MainWindow", "6"))
        self.pushButton9.setText(_translate("MainWindow", "9"))
        self.pushButton9.setShortcut(_translate("MainWindow", "9"))
        self.pushButton8.setText(_translate("MainWindow", "8"))
        self.pushButton8.setShortcut(_translate("MainWindow", "8"))
        self.pushButton7.setText(_translate("MainWindow", "7"))
        self.pushButton7.setShortcut(_translate("MainWindow", "7"))
        self.add_pushButton.setText(_translate("MainWindow", "+"))
        self.add_pushButton.setShortcut(_translate("MainWindow", "+"))
        self.minus_pushButton.setText(_translate("MainWindow", "-"))
        self.minus_pushButton.setShortcut(_translate("MainWindow", "-"))
        self.mul_pushButton.setText(_translate("MainWindow", "x"))
        self.mul_pushButton.setShortcut(_translate("MainWindow", "*"))
        self.div_pushButton.setText(_translate("MainWindow", "/"))
        self.div_pushButton.setShortcut(_translate("MainWindow", "/"))
        self.c_pushButton.setText(_translate("MainWindow", "C"))
        self.c_pushButton.setShortcut(_translate("MainWindow", "C"))
        self.pi_pushButton.setText(_translate("MainWindow", "π"))
        self.pi_pushButton.setShortcut(_translate("MainWindow", "Del"))
        self.upon_pushButton.setText(_translate("MainWindow", "⅟x"))
        self.pow_pushButton.setText(_translate("MainWindow", "xⁿ"))
        self.root_pushButton.setText(_translate("MainWindow", "√"))
        self.percent_pushButton.setText(_translate("MainWindow", "%"))
        self.percent_pushButton.setShortcut(_translate("MainWindow", "%"))
        self.back_pushButton.setText(_translate("MainWindow", "«"))
        self.back_pushButton.setShortcut(_translate("MainWindow", "Backspace"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
